// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU5N9WOGRePlM4FyUwbV77KKIp8nAgS1A',
    appId: '1:38136062640:web:cc8bf82647507e0fd9d175',
    messagingSenderId: '38136062640',
    projectId: 'projet-mobile-f95a2',
    authDomain: 'projet-mobile-f95a2.firebaseapp.com',
    storageBucket: 'projet-mobile-f95a2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBQGm6MgGUj0Pj-mSoheyvEB9bSp98j5dg',
    appId: '1:38136062640:android:8e62da0f10ff4bebd9d175',
    messagingSenderId: '38136062640',
    projectId: 'projet-mobile-f95a2',
    storageBucket: 'projet-mobile-f95a2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAU8hD6zRV0CnqdhfN-uuZPIjuUAB17qI8',
    appId: '1:38136062640:ios:8e30e9b44f88694ad9d175',
    messagingSenderId: '38136062640',
    projectId: 'projet-mobile-f95a2',
    storageBucket: 'projet-mobile-f95a2.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAU8hD6zRV0CnqdhfN-uuZPIjuUAB17qI8',
    appId: '1:38136062640:ios:8e30e9b44f88694ad9d175',
    messagingSenderId: '38136062640',
    projectId: 'projet-mobile-f95a2',
    storageBucket: 'projet-mobile-f95a2.appspot.com',
    iosBundleId: 'com.example.gtkFlutter',
  );
}
